easy_admin:
    entities:
        Article:
            class: AppBundle\Entity\Article
            list:
                fields:
                    - visible
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
                    - title
                    - synopsis
                    - category
                    - tags
                    - lang
            show:
                fields:
                    - visible
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
                    - title
                    - synopsis
                    - body
                    - category
                    - tags
                    - lang
            form:
                fields:
                    - visible
                    - { property: 'imageFile', type: 'vich_image' }
                    - title
                    - synopsis
                    - { type: 'divider' }
                    - { property: 'body', type: 'ckeditor' }
                    - { type: 'divider' }
                    - category
                    - tags
                    - { property: 'lang', type: 'choice', type_options: {choices: { 'Fr':'fr', 'En':'en' }} }
